### PR TITLE
Improve grammar

### PR DESCRIPTION
**Pull request by PatrickF1**
Hi @kidonng, exciting new plugin! Thought I'd return the favor of all the contributions you've made to fzf.fish with one of my own, albeit it's a small one. However, if you'd like, I can find some place in fzf.fish's Readme or Wiki to mention this and get you more visibility. LMK!

### CODE REVIEW

**Comment by kidonng** [comment]
Thanks a lot (both for this PR and your offering)! I'll take a look later.

About the fzf.fish wiki, is there any reason you don't want to make it publicly editable?

**Comment by PatrickF1** [comment]
> is there any reason you don't want to make it publicly editable?

The main reason is because I am treating the Wiki as actual, official docs. I want the quality and organization and focus to be as high as it is for docs that are markdown files checked into the code. That said, I can make it editable by you.

**Comment by PatrickF1** [comment]
@kidonng could you take a look please? would like to tie up my loose ends. Also I'm considering integrating preview.fish into my https://github.com/jarun/nnn set up!

**Comment by PatrickF1** [comment]
This should be a no-brainer merge. Could you take a look or I'm just gonna close this?

**Pull request closed without merging**
